# Important info
dataset_name: 'casia'
model_name: 'siameseNet'
arch: 'efficientnet_b1_pruned'

output_path: './reports'
random_seed: 42

# StratifiedShuffleSplit
train_size: 0.667
test_size: 0.333

# Datasets
final_shape: [1, 280, 320]
csv_dir: './'
dataset_dir: './'
shuffle_train: True
batch_size: 64 # batch_size

# Callbacks
wandb:
  log: 'all'
  log_preds: False
  dataset_name: 'casia'
  log_model: True
save_model:
  monitor: 'valid_loss'
  min_delta: 0.0
  fname: 'best'
  with_opt: True
  every_epoch: False
reduce_lr:
  monitor: 'valid_loss'
  min_delta: 0.1
  patience: 5

epochs: 500