# Model
model_name: 'resnetv2_50x1_bit'
resize: 224
# model:
#   model_name: 'tf_efficientnet_b0'
#   pretrained: True 
#   scriptable: True
#   exportable: True
  # Usado para resumir o treino a partir de um checkpoint
  # Caso o treino seja do zero, deixe comentado
  # checkpoint_path: None 

output_path: './reports'
random_seed: 42

learning_rate: 0.01

# StratifiedShuffleSplit
train_size: 0.667
test_size: 0.333

# Datasets
final_shape: [1, 280, 320]
csv_dir: './'
dataset_name: 'casia'
dataset_dir: './'
shuffle_train: True
batch_size: 64 # batch_size

# Callbacks
wandb:
  log: 'all'
  log_preds: False
  dataset_name: 'casia'
  log_model: True
save_model:
  monitor: 'valid_loss'
  min_delta: 0.0
  fname: 'best'
  with_opt: True
  every_epoch: False
reduce_lr:
  monitor: 'valid_loss'
  min_delta: 0.1
  patience: 10

# Train
epochs: 500
freeze_epochs: 250
start_epoch: 0
sync_tensorboard: True